"""empty message

Revision ID: 1a0e68f3ead2
Revises: aa95c321e5e3
Create Date: 2023-03-30 00:20:44.656148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a0e68f3ead2'
down_revision = 'aa95c321e5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('date_commented', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('poster_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['poster_id'], ['id'])
        batch_op.drop_column('content')
        batch_op.drop_column('date_added')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.Text(length=200), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=200), nullable=True))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('about_author')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('content', mysql.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('post_id')
        batch_op.drop_column('poster_id')
        batch_op.drop_column('date_commented')
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
