"""profile pic added

Revision ID: 502b9f9058e7
Revises: 7acfe1a4bdfd
Create Date: 2023-03-10 16:47:36.064949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502b9f9058e7'
down_revision = '7acfe1a4bdfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
