"""added password field

Revision ID: bf6564334f7c
Revises: b97864fc4164
Create Date: 2023-03-08 09:47:58.916682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf6564334f7c'
down_revision = 'b97864fc4164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('favorite_color',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('favorite_color',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
